name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install tox

    - name: Lint code
      run: tox -e lint

  unit:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install tox

    - name: Run unit tests
      run: tox -e unit

  deploy:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - uses: balchua/microk8s-actions@v0.2.2
      with:
        addons: '["dns", "storage", "rbac"]'

    - name: Install dependencies
      run: |
        set -eux
        sudo pip3 install charmcraft
        sudo snap install juju --classic
        sudo snap install juju-helpers --classic
        sudo snap install juju-wait --classic
        sudo snap install yq
        sudo apt update
        sudo apt install -y tox firefox-geckodriver

    - name: Bootstrap Juju
      run: |
        set -eux
        sg microk8s -c 'juju bootstrap microk8s uk8s'
        juju add-model kubeflow

    - name: Deploy charm
      run: |
        set -eux
        charmcraft build
        juju bundle deploy -b tests/bundle.yaml --build

        # https://bugs.launchpad.net/juju/+bug/1921739
        (i=60; while ! juju wait -wvt 30 ; do ((--i)) || exit; sleep 1; done)

    - name: Test charm with Selenium
      run: tox -e selenium

    - name: Get all
      run: kubectl get all -A
      if: failure()

    - name: Get configmaps
      run: kubectl get configmaps -A
      if: failure()

    - name: Get juju status
      run: juju status
      if: failure()

    - name: Get workload logs
      run: kubectl logs --tail 100 -nkubeflow -lapp.kubernetes.io/name=kubeflow-dashboard
      if: failure()

    - name: Get operator logs
      run: kubectl logs --tail 100 -nkubeflow -loperator.juju.is/name
      if: failure()

    - name: Upload selenium screenshots
      uses: actions/upload-artifact@v2
      with:
        name: selenium-screenshots
        path: /tmp/selenium-*.png
      if: failure()
